# Generated by Django 5.0.7 on 2024-08-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ram', models.CharField(max_length=50)),
                ('rom', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=100)),
                ('display_type', models.CharField(max_length=100)),
                ('display_size', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('network_type', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
