# Generated by Django 5.0.7 on 2024-08-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_brands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
