# Generated by Django 5.0.7 on 2024-08-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0001_initial'),
        ('Product', '0005_delete_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brands.brand'),
        ),
    ]
