# Generated by Django 5.0.7 on 2024-08-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_rename_image_variant_image4_variant_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image1',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image2',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image3',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
