# Generated by Django 5.0.7 on 2024-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='Product', to='Product.category'),
        ),
    ]
