# Generated by Django 5.0.7 on 2024-08-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
