# Generated by Django 5.0.7 on 2024-09-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='min_amount',
            field=models.IntegerField(default=0),
        ),
    ]
