# Generated by Django 5.0.7 on 2024-09-21 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0002_coupons_min_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_users',
            name='coupon_code',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Coupons.coupons'),
        ),
        migrations.AlterField(
            model_name='coupon_users',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
