# Generated by Django 5.0.7 on 2024-09-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0003_coupon_users_coupon_code_alter_coupon_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_users',
            name='coupon_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coupons.coupons'),
        ),
    ]
