# Generated by Django 5.0.7 on 2024-09-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signup_method',
            field=models.CharField(default='google'),
        ),
    ]
