# Generated by Django 5.0.7 on 2024-09-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0011_alter_variant_color_alter_variant_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_name', models.CharField()),
                ('offer_details', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.variant')),
            ],
        ),
    ]
