# Generated by Django 5.0.7 on 2024-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_offers',
            name='offer_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_offers',
            name='offer_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
