# Generated by Django 5.0.7 on 2024-09-05 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0001_initial'),
        ('Offers', '0002_alter_product_offers_offer_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_name', models.CharField(blank=True, null=True)),
                ('offer_details', models.TextField(blank=True, null=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brands.brand')),
            ],
        ),
    ]
