# Generated by Django 5.0.7 on 2024-09-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0003_brand_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_offers',
            name='offer_price',
            field=models.IntegerField(default=0),
        ),
    ]
