# Generated by Django 5.0.7 on 2024-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
