# Generated by Django 5.0.7 on 2024-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
