# Generated by Django 5.0.7 on 2024-09-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
