# Generated by Django 5.0.7 on 2024-08-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_payment_type'),
        ('Product', '0011_alter_variant_color_alter_variant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.variant'),
        ),
    ]
