# Generated by Django 5.0.7 on 2024-08-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_item_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='status',
            field=models.CharField(default='Pending', max_length=40),
        ),
    ]
