# Generated by Django 5.0.7 on 2024-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_alter_order_item_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='message',
            field=models.CharField(blank=True, default=' ', null=True),
        ),
    ]
