# Generated by Django 5.0.7 on 2024-09-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_alter_order_item_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(default='0'),
        ),
    ]
