# Generated by Django 5.0.7 on 2024-09-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_amount',
            field=models.IntegerField(default=0),
        ),
    ]
