# Generated by Django 5.0.7 on 2024-09-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_order_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='coupon_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
