# Generated by Django 5.0.7 on 2024-09-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_order_item_coupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='coupon_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
